# Generated by Django 4.1.4 on 2022-12-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulk_order",
            name="address",
            field=models.TextField(),
        ),
    ]
