# Generated by Django 4.1.4 on 2022-12-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_bulk_order_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulk_order",
            name="number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="bulk_order",
            name="zip_code",
            field=models.CharField(max_length=50),
        ),
    ]
