# Generated by Django 4.1.4 on 2022-12-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_bulk_order_number_alter_bulk_order_zip_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.IntegerField()),
                ("re_enter_password", models.IntegerField()),
            ],
        ),
    ]
