# Generated by Django 4.1.4 on 2022-12-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="user",
            new_name="customers",
        ),
    ]
