# Generated by Django 4.1.4 on 2022-12-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_rename_user_customers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="password",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="customers",
            name="re_enter_password",
            field=models.CharField(max_length=20),
        ),
    ]
